repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.49.11
    hooks:
      - id: swiftformat
  - repo: https://github.com/realm/SwiftLint
    rev: 0.47.1
    hooks:
      - id: swiftlint
