name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    strategy:
      matrix:
        platform: ["iOS Simulator,name=iPhone 13 Pro Max", "macOS"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check XCTest requirement
        id: xctest_requirement
        run: |
          file_pattern=".github/workflows|.swiftpm|Sources|Tests|.swift-version|Package.swift"
          diff="$(git diff --name-only HEAD^ HEAD | grep -E '$file_pattern')"
          if [[ ${#diff[@]} -gt 0 ]]; then
            echo "::set-output name=is_required::1"
          fi
      - name: XCTest
        if: ${{ steps.xctest_requirement.outputs.is_required }}
        run: xcodebuild test -scheme Roots -destination platform="${{ matrix.platform }}"
